### ISSUE TITLE
TGM notice appears on the Site Health page

### ISSUE THREAD

**Issue by cssjoe** [BoldGrid/boldgrid-theme-framework#104]
**Describe the bug**
The TGM notice to install/activate plugins should not be displayed on the Site Health ("wp-admin/site-health.php") page (in WordPress >=5.2).

**To Reproduce**
1. Have a premium Connect Key and deactivate a premium plugin.
2. Go to the Site Health page ("wp-admin/site-health.php").
The notice is displayed under the header and above the status heading.

**Expected behavior**
There should be no notices.

**Comment by timelsass** [comment]
TGM creates a global admin notice, so it's meant to show on every page in the admin.  A _**user can**_ selectively hide the notice on page load of this particular page by closing the notice, or globally keep it from coming back on any pages in the admin by dismissing the notice.

Also of note, if/when we move forward with the new theme dashboard, BoldGrid based themes will most likely not have a need for TGM anymore, and instead show a single notice on theme activation to prompt a user to undergo onboarding in the theme's dashboard.

Is it possible? Yes, sure.  Why not on `/tools.php?page=export_personal_data`, `widgets.php`, `edit-comments.php` or the dozens of other pages WordPress has by default, not to mention the pages created by various plugins?  I just don't see any justification for BGTFW to selectively hide a notice here, and only on this one particular page - especially since it's not related to or a page created by the theme.
