### ISSUE TITLE
Feature: Add the ability to hide browser hover text

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/boldgrid-theme-framework#110]
**Is your feature request related to a problem? Please describe.**
When the hover label activates, it can block the menu items. If you have a drop-down menu and users are trying to decide which page they want to go to, they are partially blocked from seeing the page titles.

**Describe the solution you'd like**
Having the option to turn this feature off would help mitigate this problem.

**Describe alternatives you've considered**
Removing the text from the Title attribute for menu items in the Customizer does not prevent this from displaying.  The other considered option is to change the pointer-events CSS rule, but that makes the menu unusable.

**Additional context**
![image](https://user-images.githubusercontent.com/45979457/58588600-01b11600-822e-11e9-88c0-9f68e9a43ad1.png)

**Comment by timelsass** [comment]
This is an issue for themes based on the v1 framework, and v2 based themes do not use the bootstrap navwalker stuff anymore.  This only impacts the primary menu locations (from what I can recall) since those are the only ones using the bootstrap navwalker.  

There's two ways this can be handled:

1. Filter the nav menu item attributes (Recommended).
The first way is to filter the actual nav menu item attributes using the `nav_menu_link_attributes` filter in WordPress.  The problem that is occurring is at some point it was decided that the title attribute should be prefilled with the link's text.  This was most likely added for the BoldGrid/boldgrid-inspirations plugin when it installs a primary menu.  There's not a need for this in the framework as we do generate the title attributes for social menu items that are added, so BoldGrid/boldgrid-inspirations could handle doing this when it creates up it's menus it installs if it's really necessary.  In terms of fixing the problem for current users today - this can be done by creating a child theme and adding the following code to `functions.php` in it:

```php
add_filter( 'nav_menu_link_attributes', function( $atts, $item ) {
	$atts['title'] = ! empty( $item->attr_title ) ? $item->attr_title : '';
	return $atts;
}, 15, 2 );
```
To save the hassle of actually creating a child theme, you can use the plugin made from the following gist:
[[code](https://gist.github.com/timelsass/c4e445f6fef189aa843ddf251586b2d4)] | [[zip](https://gist.github.com/timelsass/c4e445f6fef189aa843ddf251586b2d4/archive/2693aaf9d0d858dc8312b640415c9cdc6414fb22.zip)]

I've attached the plugin zip here for distribution to users who may need it before a patch is rolled out to all of the v1 based themes we distribute:
[bgtfw-allow-nav-menu-link-title-attributes.zip](https://github.com/BoldGrid/boldgrid-theme-framework/files/3249803/bgtfw-allow-nav-menu-link-title-attributes.zip)

2. Use JS to toggle the title attribute.
Another way for a current v1 based theme to handle this would be using javascript.  This is the non-jquery JS that could be added in the customizer's Custom CSS/JS section's JS editor:

```js
document.querySelectorAll( '#site-navigation.navbar li a' ).forEach( function( link ) {
	link.onmouseenter = function() {
		link.dataset.title = link.title;
		link.title = '';
	};
	link.onmouseleave = function() {
		link.title = link.dataset.title;
	};
}  );
```

This would essentially replace the title's with empty strings on hover, and store the title attributes as a data attribute, so they can be restored when the mouse is no longer hovering.  This will help keep the title attributes in tact for accessibility reasons and keep the title attribute on page load for SEO reasons, but get rid of the visual aide when hovering.

There's not any implications requiring the user to remove/disable/delete/leave either of the two solutions above once a patch is rolled out.  I think the best solution is to use the plugin version provided as the JS solution could have a very minor performance hit if the code is left running once a patch comes out.  No need to switch attributes and store the old one client side once the problem is fixed.  Additionally the filter method is the safest bet to ensure a smoother transition when migrating to v2 to avoid conflicts that the JS solutions would have (different DOM selectors).

----------------------------------

I did tag and release BGTFW v1.6.1 with the patch, but this hasn't been applied and rolled out to all v1 themes.  I'm not sure when it will, and there's always a possibility that the upgrade to v2 might come before there's a chance.
