### ISSUE TITLE
Fresh site starter content throws error

### ISSUE THREAD

**Issue by rramo012** [BoldGrid/boldgrid-theme-framework#122]
**Describe the bug**
The following warning is thrown when fresh_site = 1 & a user enters the customizer

PHP Warning:  preg_match() expects parameter 2 to be string, array given in /var/www/html/wp-includes/class-wp-customize-manager.php on line 1544

**To Reproduce**
1. Set the database option fresh_site = 1
2. Click on customize
3. See error

**Comment by bwmarkle** [comment]
Needs to be fixed in WordPress core. @timelsass has patch - https://core.trac.wordpress.org/ticket/45484 that is awaiting approval.

**Comment by timelsass** [comment]
Yeah I've been trying to get traction on that issue, but still have not gotten any sort of response or approval.  The only thing on that ticket I could suggest is maybe adding some unit tests to update the ticket with has tests.  The code itself could be consolidated and rewritten, but I didn't want to edit what was already there too much, unless someone approving/merging indicated I should.  I really hope they get this merged in, it's been quite a while since the initial report and patch.

**Comment by timelsass** [comment]
this ticket can now be closed as I was able to get some traction on the ticket and my patch was [merged in the wp 5.3 release](https://core.trac.wordpress.org/ticket/45484#comment:17). 🎉 

tested and no longer is an issue with this patch in place.

**Comment by jamesros161** [comment]
See above. Issue was patched in wp 5.3 release
