### ISSUE TITLE
Neutral Color not pulling into editor for custom templates.

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/boldgrid-theme-framework#547]
The neutral color doesn't pull thru to the custom footer so I have white text on a white background right now.

![image](https://user-images.githubusercontent.com/20601160/144895077-35e58c00-4653-4fd4-b1af-65a77db371d3.gif)

**Comment by nicolepaschen** [comment]
RC1

The neutral color (last palette position) is black. When I'm in the Sticky Header Template I see the correct color.
On the front end and in the Customizer preview, it applies color5 as the background color instead of the neutral color. 
Likely related to #529 because I didn't start with starter content or Inspirations

![sticky-header-neutral](https://user-images.githubusercontent.com/20601160/145862784-58f2ee6e-0a38-437e-9ad0-7357e937d825.gif)

**Comment by nicolepaschen** [comment]
Actually I think it's just using the Customizer setting for the header background color. Custom Sticky Headers should use the background from the sticky header template
