### ISSUE TITLE
Generate RTL styles

### ISSUE THREAD

**Issue by timelsass** [BoldGrid/boldgrid-theme-framework#61]
Currently our CSS is split up into various parts, and during the build process we don't have any transforms added to create RTL styles.  We should look at consolidating some of this CSS, and also look into piping through something like postcss to create RTL styles.  Themes would then be able to be tagged as having support for this.

**Comment by jessecowens** [comment]
Upvoting this issue based on user feedback:

> Message: Hi
I am building my site using boldgrid. Our site is going to be multilingual. We have just decided to add a Persian version too. The problem is boldgrid doesn't seem to support right to left languages. I have a licensed Persian font which I want to use in my site. I have tried the procedure recommended by the producers for installation. However I have failed. It's seems to me that the rtl.css file in boldgrid is different from that of the other WordPress sites. That's why I can't follow the installation procedure closely.
>I would appreciate it if you could help me with this.
